version: '3.1'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: m06
      MYSQL_USER: ilerna
      MYSQL_PASSWORD: ilerna_1234
      MYSQL_ROOT_PASSWORD: patatasada
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
